In [342]:
import pandas as pd
import numpy as np

In [343]:
def load_data(file_path):
    
    data = pd.read_csv(file_path, skiprows = 1)
    
    df_csv = pd.DataFrame(data)
    
    df_csv.rename(columns= {'01 !':'Gold', '02 !':'Silve', '03 !':'Bronze'}, inplace = True)
    
    #split the unnamed column into two columns 
    df_csv[['Country name','Country code']] = pd.DataFrame(df_csv['Unnamed: 0'].str.split('\xa0').tolist() )
    
    df_csv.index = df_csv['Country name'] # change index to country name
    
    df_csv.drop(['Country name','Unnamed: 0', 'Total'], axis = 1, inplace = True) # deleting country and Unnamed :0 columns
    
    
    # rearrange the columns 
    df_csv = df_csv[['Country code','# Summer', 'Gold', 'Silve', 'Bronze', '# Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '# Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total', ]]
    
    #remove extra extra character
    df_csv['Country code'] = df_csv['Country code'].astype(str).apply(lambda x: x.split(" ",1)[0])
    
    print(df_csv.columns)
    display(df_csv) #to print whole dataframe

In [344]:
file_path = '../data/olympics.csv'
load_data(file_path)

Index(['Country code', '# Summer', 'Gold', 'Silve', 'Bronze', '# Winter',
       '01 !.1', '02 !.1', '03 !.1', 'Total.1', '# Games', '01 !.2', '02 !.2',
       '03 !.2', 'Combined total'],
      dtype='object')

,Country code,# Summer,Gold,Silve,Bronze,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
Country name,,,,,,,,,,,,,,,
Afghanistan,(AFG),13,0,0,2,0,0,0,0,0,13,0,0,2,2
Algeria,(ALG),12,5,2,8,3,0,0,0,0,15,5,2,8,15
Argentina,(ARG),23,18,24,28,18,0,0,0,0,41,18,24,28,70
Armenia,(ARM),5,1,2,9,6,0,0,0,0,11,1,2,9,12
Australasia,(ANZ),2,3,4,5,0,0,0,0,0,2,3,4,5,12
Australia,(AUS),25,139,152,177,18,5,3,4,12,43,144,155,181,480
Austria,(AUT),26,18,33,35,22,59,78,81,218,48,77,111,116,304
Azerbaijan,(AZE),5,6,5,15,5,0,0,0,0,10,6,5,15,26
Bahamas,(BAH),15,5,2,5,0,0,0,0,0,15,5,2,5,12
Bahrain,(BRN),8,0,0,1,0,0,0,0,0,8,0,0,1,1
Barbados,(BAR),11,0,0,1,0,0,0,0,0,11,0,0,1,1
Belarus,(BLR),5,12,24,39,6,6,4,5,15,11,18,28,44,90
Belgium,(BEL),25,37,52,53,20,1,1,3,5,45,38,53,56,147
Bermuda,(BER),17,0,0,1,7,0,0,0,0,24,0,0,1,1
Bohemia,(BOH),3,0,1,3,0,0,0,0,0,3,0,1,3,4
Botswana,(BOT),9,0,1,0,0,0,0,0,0,9,0,1,0,1
Brazil,(BRA),21,23,30,55,7,0,0,0,0,28,23,30,55,108
British West Indies,(BWI),1,0,0,2,0,0,0,0,0,1,0,0,2,2
Bulgaria,(BUL),19,51,85,78,19,1,2,3,6,38,52,87,81,220
Burundi,(BDI),5,1,0,0,0,0,0,0,0,5,1,0,0,1
Cameroon,(CMR),13,3,1,1,1,0,0,0,0,14,3,1,1,5
Canada,(CAN),25,59,99,121,22,62,56,52,170,47,121,155,173,449
Chile,(CHI),22,2,7,4,16,0,0,0,0,38,2,7,4,13
China,(CHN),9,201,146,126,10,12,22,19,53,19,213,168,145,526
Colombia,(COL),18,2,6,11,1,0,0,0,0,19,2,6,11,19
Costa Rica,(CRC),14,1,1,2,6,0,0,0,0,20,1,1,2,4
Ivory Coast,(CIV),12,0,1,0,0,0,0,0,0,12,0,1,0,1
Croatia,(CRO),6,6,7,10,7,4,6,1,11,13,10,13,11,34
Cuba,(CUB),19,72,67,70,0,0,0,0,0,19,72,67,70,209
Cyprus,(CYP),9,0,1,0,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka,(SRI),16,0,2,0,0,0,0,0,0,16,0,2,0,2
Sudan,(SUD),11,0,1,0,0,0,0,0,0,11,0,1,0,1
Suriname,(SUR),11,1,0,1,0,0,0,0,0,11,1,0,1,2
Sweden,(SWE),26,143,164,176,22,50,40,54,144,48,193,204,230,627
Switzerland,(SUI),27,47,73,65,22,50,40,48,138,49,97,113,113,323
Syria,(SYR),12,1,1,1,0,0,0,0,0,12,1,1,1,3
Chinese Taipei,(TPE),13,2,7,12,11,0,0,0,0,24,2,7,12,21
Tajikistan,(TJK),5,0,1,2,4,0,0,0,0,9,0,1,2,3
Tanzania,(TAN),12,0,2,0,0,0,0,0,0,12,0,2,0,2
Thailand,(THA),15,7,6,11,3,0,0,0,0,18,7,6,11,24
Togo,(TOG),9,0,0,1,1,0,0,0,0,10,0,0,1,1
Tonga,(TGA),8,0,1,0,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago,(TRI),16,2,5,11,3,0,0,0,0,19,2,5,11,18
Tunisia,(TUN),13,3,3,4,0,0,0,0,0,13,3,3,4,10
Turkey,(TUR),21,39,25,24,16,0,0,0,0,37,39,25,24,88
Uganda,(UGA),14,2,3,2,0,0,0,0,0,14,2,3,2,7
Ukraine,(UKR),5,33,27,55,6,2,1,4,7,11,35,28,59,122
United Arab Emirates,(UAE),8,1,0,0,0,0,0,0,0,8,1,0,0,1
United States,(USA),26,976,757,666,22,96,102,84,282,48,1072,859,750,2681
Uruguay,(URU),20,2,2,6,1,0,0,0,0,21,2,2,6,10
Uzbekistan,(UZB),5,5,5,10,6,1,0,0,1,11,6,5,10,21
Venezuela,(VEN),17,2,2,8,4,0,0,0,0,21,2,2,8,12
Vietnam,(VIE),14,0,2,0,0,0,0,0,0,14,0,2,0,2
Virgin Islands,(ISV),11,0,1,0,7,0,0,0,0,18,0,1,0,1
Yugoslavia,(YUG),16,26,29,28,14,0,3,1,4,30,26,32,29,87
Independent Olympic Participants,(IOP),1,0,1,2,0,0,0,0,0,1,0,1,2,3
Zambia,(ZAM),12,0,1,1,0,0,0,0,0,12,0,1,1,2
Zimbabwe,(ZIM),12,3,4,1,1,0,0,0,0,13,3,4,1,8
Mixed team,(ZZX),3,8,5,4,0,0,0,0,0,3,8,5,4,17
Totals,None,27,4809,4775,5130,22,959,958,948,2865,49,5768,5733,6078,17579