In [1004]:
import pandas as pd
import numpy as np

In [1005]:
def load_data(file_path):
    
    data = pd.read_csv(file_path, skiprows = 1)
    
    df_csv = pd.DataFrame(data)
    
    #renaming columns
    df_csv.rename(columns= {'01 !':'Gold', '02 !':'Silver', '03 !':'Bronze','01 !.2':'Gold', '02 !.2':'Silver', '03 !.2':'Bronze','01 !.1':'Gold', '02 !.1':'Silver', '03 !.1':'Bronze'}, inplace = True)
    
    #split the unnamed column into two columns 
    df_csv[['Country name','Country code']] = pd.DataFrame(df_csv['Unnamed: 0'].str.split('\xa0').tolist() )
    
    df_csv.index = df_csv['Country name'] # change index to country name
    
    df_csv.drop(['Country name','Unnamed: 0', 'Total', 'Total.1'], axis = 1, inplace = True) # deleting country and Unnamed :0 columns
     
    
    #remove extra extra character
    df_csv['Country code'] = df_csv['Country code'].astype(str).apply(lambda x: x.split(" ",1)[0])
    
    df_csv.drop(['Totals'], axis = 0, inplace = True)
    
    
    return df_csv

In [1006]:
def first_country(df):
    
    return df.iloc[0]

In [1007]:
def gold_medal(df):
    
    """ take data frame then select gold column of summer games and after that sort values in descending order """
    
    return df['Gold'].iloc[:,0].sort_values(ascending = False).index[0]

In [1008]:
def biggest_difference(df):
    summer_gold = df['Gold'].iloc[:,0]
    winter_gold = df['Gold'].iloc[:,1].sort_values(ascending = False)
    return (abs(summer_gold -winter_gold)).sort_values(ascending = False).index[0]

In [1009]:
def get_points(df):
    gold = df['Gold'].iloc[:,0] + df['Gold'].iloc[:,1] + df['Gold'].iloc[:,2]
    silver = df['Silver'].iloc[:,0] + df['Silver'].iloc[:,1] + df['Silver'].iloc[:,2]
    bronze = df['Bronze'].iloc[:,0] + df['Bronze'].iloc[:,1] + df['Bronze'].iloc[:,2]
    
    total_points = (gold * 3 + silver *2 + bronze*1)
    return total_points.sort_values(ascending = False)

In [1010]:
def __main__():
    file_path = '../data/olympics.csv'
    display(load_data(file_path)) #for displaying whole dataframe
    df = load_data(file_path)
    print('Details of first country')
    print(first_country(df))
    
    print('country has won  most gold in summer games')
    print(gold_medal(df))
    
    print('biggest difference between their summner and winter gold medal count')
    print(biggest_difference(df))
    
    print('points')
    points  = get_points(df)
    df['points'] = points
    
    display(df)

In [1011]:
__main__()

,# Summer,Gold,Silver,Bronze,# Winter,Gold,Silver,Bronze,# Games,Gold,Silver,Bronze,Combined total,Country code
Country name,,,,,,,,,,,,,,
Afghanistan,13,0,0,2,0,0,0,0,13,0,0,2,2,(AFG)
Algeria,12,5,2,8,3,0,0,0,15,5,2,8,15,(ALG)
Argentina,23,18,24,28,18,0,0,0,41,18,24,28,70,(ARG)
Armenia,5,1,2,9,6,0,0,0,11,1,2,9,12,(ARM)
Australasia,2,3,4,5,0,0,0,0,2,3,4,5,12,(ANZ)
Australia,25,139,152,177,18,5,3,4,43,144,155,181,480,(AUS)
Austria,26,18,33,35,22,59,78,81,48,77,111,116,304,(AUT)
Azerbaijan,5,6,5,15,5,0,0,0,10,6,5,15,26,(AZE)
Bahamas,15,5,2,5,0,0,0,0,15,5,2,5,12,(BAH)
Bahrain,8,0,0,1,0,0,0,0,8,0,0,1,1,(BRN)
Barbados,11,0,0,1,0,0,0,0,11,0,0,1,1,(BAR)
Belarus,5,12,24,39,6,6,4,5,11,18,28,44,90,(BLR)
Belgium,25,37,52,53,20,1,1,3,45,38,53,56,147,(BEL)
Bermuda,17,0,0,1,7,0,0,0,24,0,0,1,1,(BER)
Bohemia,3,0,1,3,0,0,0,0,3,0,1,3,4,(BOH)
Botswana,9,0,1,0,0,0,0,0,9,0,1,0,1,(BOT)
Brazil,21,23,30,55,7,0,0,0,28,23,30,55,108,(BRA)
British West Indies,1,0,0,2,0,0,0,0,1,0,0,2,2,(BWI)
Bulgaria,19,51,85,78,19,1,2,3,38,52,87,81,220,(BUL)
Burundi,5,1,0,0,0,0,0,0,5,1,0,0,1,(BDI)
Cameroon,13,3,1,1,1,0,0,0,14,3,1,1,5,(CMR)
Canada,25,59,99,121,22,62,56,52,47,121,155,173,449,(CAN)
Chile,22,2,7,4,16,0,0,0,38,2,7,4,13,(CHI)
China,9,201,146,126,10,12,22,19,19,213,168,145,526,(CHN)
Colombia,18,2,6,11,1,0,0,0,19,2,6,11,19,(COL)
Costa Rica,14,1,1,2,6,0,0,0,20,1,1,2,4,(CRC)
Ivory Coast,12,0,1,0,0,0,0,0,12,0,1,0,1,(CIV)
Croatia,6,6,7,10,7,4,6,1,13,10,13,11,34,(CRO)
Cuba,19,72,67,70,0,0,0,0,19,72,67,70,209,(CUB)
Cyprus,9,0,1,0,10,0,0,0,19,0,1,0,1,(CYP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spain,22,37,59,35,19,1,0,1,41,38,59,36,133,(ESP)
Sri Lanka,16,0,2,0,0,0,0,0,16,0,2,0,2,(SRI)
Sudan,11,0,1,0,0,0,0,0,11,0,1,0,1,(SUD)
Suriname,11,1,0,1,0,0,0,0,11,1,0,1,2,(SUR)
Sweden,26,143,164,176,22,50,40,54,48,193,204,230,627,(SWE)
Switzerland,27,47,73,65,22,50,40,48,49,97,113,113,323,(SUI)
Syria,12,1,1,1,0,0,0,0,12,1,1,1,3,(SYR)
Chinese Taipei,13,2,7,12,11,0,0,0,24,2,7,12,21,(TPE)
Tajikistan,5,0,1,2,4,0,0,0,9,0,1,2,3,(TJK)
Tanzania,12,0,2,0,0,0,0,0,12,0,2,0,2,(TAN)
Thailand,15,7,6,11,3,0,0,0,18,7,6,11,24,(THA)
Togo,9,0,0,1,1,0,0,0,10,0,0,1,1,(TOG)
Tonga,8,0,1,0,1,0,0,0,9,0,1,0,1,(TGA)
Trinidad and Tobago,16,2,5,11,3,0,0,0,19,2,5,11,18,(TRI)
Tunisia,13,3,3,4,0,0,0,0,13,3,3,4,10,(TUN)
Turkey,21,39,25,24,16,0,0,0,37,39,25,24,88,(TUR)
Uganda,14,2,3,2,0,0,0,0,14,2,3,2,7,(UGA)
Ukraine,5,33,27,55,6,2,1,4,11,35,28,59,122,(UKR)
United Arab Emirates,8,1,0,0,0,0,0,0,8,1,0,0,1,(UAE)
United States,26,976,757,666,22,96,102,84,48,1072,859,750,2681,(USA)
Uruguay,20,2,2,6,1,0,0,0,21,2,2,6,10,(URU)
Uzbekistan,5,5,5,10,6,1,0,0,11,6,5,10,21,(UZB)
Venezuela,17,2,2,8,4,0,0,0,21,2,2,8,12,(VEN)
Vietnam,14,0,2,0,0,0,0,0,14,0,2,0,2,(VIE)
Virgin Islands,11,0,1,0,7,0,0,0,18,0,1,0,1,(ISV)
Yugoslavia,16,26,29,28,14,0,3,1,30,26,32,29,87,(YUG)
Independent Olympic Participants,1,0,1,2,0,0,0,0,1,0,1,2,3,(IOP)
Zambia,12,0,1,1,0,0,0,0,12,0,1,1,2,(ZAM)
Zimbabwe,12,3,4,1,1,0,0,0,13,3,4,1,8,(ZIM)
Mixed team,3,8,5,4,0,0,0,0,3,8,5,4,17,(ZZX)

Details of first country
# Summer             13
Gold                  0
Silver                0
Bronze                2
# Winter              0
Gold                  0
Silver                0
Bronze                0
# Games              13
Gold                  0
Silver                0
Bronze                2
Combined total        2
Country code      (AFG)
Name: Afghanistan, dtype: object
country has won  most gold in summer games
United States
biggest difference between their summner and winter gold medal count
United States
points

,# Summer,Gold,Silver,Bronze,# Winter,Gold,Silver,Bronze,# Games,Gold,Silver,Bronze,Combined total,Country code,points
Country name,,,,,,,,,,,,,,,
Afghanistan,13,0,0,2,0,0,0,0,13,0,0,2,2,(AFG),4
Algeria,12,5,2,8,3,0,0,0,15,5,2,8,15,(ALG),54
Argentina,23,18,24,28,18,0,0,0,41,18,24,28,70,(ARG),260
Armenia,5,1,2,9,6,0,0,0,11,1,2,9,12,(ARM),32
Australasia,2,3,4,5,0,0,0,0,2,3,4,5,12,(ANZ),44
Australia,25,139,152,177,18,5,3,4,43,144,155,181,480,(AUS),1846
Austria,26,18,33,35,22,59,78,81,48,77,111,116,304,(AUT),1138
Azerbaijan,5,6,5,15,5,0,0,0,10,6,5,15,26,(AZE),86
Bahamas,15,5,2,5,0,0,0,0,15,5,2,5,12,(BAH),48
Bahrain,8,0,0,1,0,0,0,0,8,0,0,1,1,(BRN),2
Barbados,11,0,0,1,0,0,0,0,11,0,0,1,1,(BAR),2
Belarus,5,12,24,39,6,6,4,5,11,18,28,44,90,(BLR),308
Belgium,25,37,52,53,20,1,1,3,45,38,53,56,147,(BEL),552
Bermuda,17,0,0,1,7,0,0,0,24,0,0,1,1,(BER),2
Bohemia,3,0,1,3,0,0,0,0,3,0,1,3,4,(BOH),10
Botswana,9,0,1,0,0,0,0,0,9,0,1,0,1,(BOT),4
Brazil,21,23,30,55,7,0,0,0,28,23,30,55,108,(BRA),368
British West Indies,1,0,0,2,0,0,0,0,1,0,0,2,2,(BWI),4
Bulgaria,19,51,85,78,19,1,2,3,38,52,87,81,220,(BUL),822
Burundi,5,1,0,0,0,0,0,0,5,1,0,0,1,(BDI),6
Cameroon,13,3,1,1,1,0,0,0,14,3,1,1,5,(CMR),24
Canada,25,59,99,121,22,62,56,52,47,121,155,173,449,(CAN),1692
Chile,22,2,7,4,16,0,0,0,38,2,7,4,13,(CHI),48
China,9,201,146,126,10,12,22,19,19,213,168,145,526,(CHN),2240
Colombia,18,2,6,11,1,0,0,0,19,2,6,11,19,(COL),58
Costa Rica,14,1,1,2,6,0,0,0,20,1,1,2,4,(CRC),14
Ivory Coast,12,0,1,0,0,0,0,0,12,0,1,0,1,(CIV),4
Croatia,6,6,7,10,7,4,6,1,13,10,13,11,34,(CRO),134
Cuba,19,72,67,70,0,0,0,0,19,72,67,70,209,(CUB),840
Cyprus,9,0,1,0,10,0,0,0,19,0,1,0,1,(CYP),4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spain,22,37,59,35,19,1,0,1,41,38,59,36,133,(ESP),536
Sri Lanka,16,0,2,0,0,0,0,0,16,0,2,0,2,(SRI),8
Sudan,11,0,1,0,0,0,0,0,11,0,1,0,1,(SUD),4
Suriname,11,1,0,1,0,0,0,0,11,1,0,1,2,(SUR),8
Sweden,26,143,164,176,22,50,40,54,48,193,204,230,627,(SWE),2434
Switzerland,27,47,73,65,22,50,40,48,49,97,113,113,323,(SUI),1260
Syria,12,1,1,1,0,0,0,0,12,1,1,1,3,(SYR),12
Chinese Taipei,13,2,7,12,11,0,0,0,24,2,7,12,21,(TPE),64
Tajikistan,5,0,1,2,4,0,0,0,9,0,1,2,3,(TJK),8
Tanzania,12,0,2,0,0,0,0,0,12,0,2,0,2,(TAN),8
Thailand,15,7,6,11,3,0,0,0,18,7,6,11,24,(THA),88
Togo,9,0,0,1,1,0,0,0,10,0,0,1,1,(TOG),2
Tonga,8,0,1,0,1,0,0,0,9,0,1,0,1,(TGA),4
Trinidad and Tobago,16,2,5,11,3,0,0,0,19,2,5,11,18,(TRI),54
Tunisia,13,3,3,4,0,0,0,0,13,3,3,4,10,(TUN),38
Turkey,21,39,25,24,16,0,0,0,37,39,25,24,88,(TUR),382
Uganda,14,2,3,2,0,0,0,0,14,2,3,2,7,(UGA),28
Ukraine,5,33,27,55,6,2,1,4,11,35,28,59,122,(UKR),440
United Arab Emirates,8,1,0,0,0,0,0,0,8,1,0,0,1,(UAE),6
United States,26,976,757,666,22,96,102,84,48,1072,859,750,2681,(USA),11368
Uruguay,20,2,2,6,1,0,0,0,21,2,2,6,10,(URU),32
Uzbekistan,5,5,5,10,6,1,0,0,11,6,5,10,21,(UZB),76
Venezuela,17,2,2,8,4,0,0,0,21,2,2,8,12,(VEN),36
Vietnam,14,0,2,0,0,0,0,0,14,0,2,0,2,(VIE),8
Virgin Islands,11,0,1,0,7,0,0,0,18,0,1,0,1,(ISV),4
Yugoslavia,16,26,29,28,14,0,3,1,30,26,32,29,87,(YUG),342
Independent Olympic Participants,1,0,1,2,0,0,0,0,1,0,1,2,3,(IOP),8
Zambia,12,0,1,1,0,0,0,0,12,0,1,1,2,(ZAM),6
Zimbabwe,12,3,4,1,1,0,0,0,13,3,4,1,8,(ZIM),36
Mixed team,3,8,5,4,0,0,0,0,3,8,5,4,17,(ZZX),76